services:
    php:
        build: .
        ports:
        - "80:80"
        volumes:
        - .:/var/www/html
        networks:
        - lmspoc-network
        extra_hosts:
        - "host.docker.internal:host-gateway"

networks:
    lmspoc-network:
        driver: bridge
